name: Build request
description: Submit code to build
title: "[Build]: "

body:
  - type: textarea
    id: code
    attributes:
      label: Code
      description: "Submit LaTeX code to build."
      render: latex
      value: |
        %%build


        % Write your LaTeX code here.


        %%dliub
    validations:
      required: true
